config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :api do
    
    namespace :v1, defaults:{format: 'json'} do
      
      get '/ingredients_search', to: 'ingredients#ingredients_search'

      get '/workflows_search', to: 'workflows#workflows_search'
      

      post '/create_user', to: 'authentications#create_user'

      get '/user_profile', to: 'users#user_profile'

      match "/users" => 'users#update', via: [:put, :patch]
      
      delete '/users', to: 'users#destroy'

      get '/users', to: 'users#show'

      get '/password_reset', to: 'users#send_password_reset'

      post '/password_reset', to: 'users#reset_password'

       
      match "/recipe_items" => "recipe_items#update", via: [:put, :patch]

      delete '/recipe_items', to: 'recipe_items#destroy'
      
      get '/recipe_items', to: 'recipe_items#show'

      get '/steps', to: 'steps#show'

      delete '/steps', to: 'steps#destroy'

      match "/steps" => "steps#update", via: [:put, :patch]

      resources :recipe_items
        
      resources :steps
     
      resources :cards
       
      resources :workflows

      resources :ingredients

    end
  
  end

end

app/models/workflow.rb
class Workflow
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  extend SearchName
  
  field :user_id, type: BSON::ObjectId
  field :name, type: String
  field :ext_image_url, type: String
  field :image, type: String
  
  # relations
  belongs_to :user

end

app/controllers/api/v1/workflows_controller.rb
class Api::V1::WorkflowsController < Api::V1::BaseController
  before_action :set_workflow, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :workflows_search]

  # GET /workflows.json
  def index
    @workflows = Workflow.all
    render json: @workflows
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # GET /workflows/1.json
  def show
    render json: @workflow
  rescue => e
    render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # POST /workflows.json
  def create
    @workflow = current_user.workflows.new(workflow_params)
    if @workflow.save
      render json: @workflow 
    else
      render json: @workflow.errors
    end
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # PATCH/PUT /workflows/1.json
  def update
    if @workflow.update(workflow_params)
      render json: @workflow
    else
      render json: @workflow.errors
    end
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # DELETE /workflows/1.json
  def destroy
    @workflow.destroy
    render json: { head: :no_content }
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end


  # GET /workflow_search
  def workflows_search
    render json: Workflow.search(params[:q])
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow
      @workflow = Workflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_params
      params.require(:workflow).permit(:name, :ext_image_url, :image)
    end
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :set_workflow, only: [:show, :edit, :update, :destroy]

  # GET /workflows
  # GET /workflows.json
  def index
    @workflows = Workflow.all
    render json: @ingredients
  end

  # GET /workflows/1
  # GET /workflows/1.json
  def show
  end

  # GET /workflows/new
  def new
    @workflow = Workflow.new
  end

  # GET /workflows/1/edit
  def edit
  end

  # POST /workflows
  # POST /workflows.json
  def create
    @workflow = current_user.workflows.new(workflow_params)

    respond_to do |format|
      if @workflow.save
        format.html { redirect_to @workflow, notice: 'Workflow was successfully created.' }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { render :new }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflows/1
  # PATCH/PUT /workflows/1.json
  def update
    respond_to do |format|
      if @workflow.update(workflow_params)
        format.html { redirect_to @workflow, notice: 'Workflow was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow }
      else
        format.html { render :edit }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflows/1
  # DELETE /workflows/1.json
  def destroy
    @workflow.destroy
    respond_to do |format|
      format.html { redirect_to workflows_url, notice: 'Workflow was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # GET /workflow_search
  def workflows_search
    render json: Workflow.search(params[:q])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow
      @workflow = Workflow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_params
      params.require(:workflow).permit(:name, :ext_image_url, :image)
    end
end

app/helpers/workflows_helper.rb
module WorkflowsHelper
end

app/views/workflows/_form.html.erb
<%= form_for(@workflow) do |f| %>
  <% if @workflow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workflow.errors.count, "error") %> prohibited this workflow from being saved:</h2>

      <ul>
      <% @workflow.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ext_image_url %><br>
    <%= f.text_field :ext_image_url %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workflows/edit.html.erb
<h1>Editing workflow</h1>

<%= render 'form' %>

<%= link_to 'Show', @workflow %> |
<%= link_to 'Back', workflows_path %>

app/views/workflows/index.html.erb
<h1>Listing workflows</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ext image url</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflows.each do |workflow| %>
      <tr>
        <td><%= workflow.name %></td>
        <td><%= workflow.ext_image_url %></td>
        <td><%= workflow.image %></td>
        <td><%= link_to 'Show', workflow %></td>
        <td><%= link_to 'Edit', edit_workflow_path(workflow) %></td>
        <td><%= link_to 'Destroy', workflow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow', new_workflow_path %>

app/views/workflows/new.html.erb
<h1>New workflow</h1>

<%= render 'form' %>

<%= link_to 'Back', workflows_path %>

app/views/workflows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workflow.name %>
</p>

<p>
  <strong>Ext image url:</strong>
  <%= @workflow.ext_image_url %>
</p>

<p>
  <strong>Image:</strong>
  <%= @workflow.image %>
</p>

<%= link_to 'Edit', edit_workflow_path(@workflow) %> |
<%= link_to 'Back', workflows_path %>