config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :api do
    
    namespace :v1, defaults:{format: 'json'} do
      
      get '/ingredients_search', to: 'ingredients#ingredients_search'

      get '/workflows_search', to: 'workflows#workflows_search'
      

      post '/create_user', to: 'authentications#create_user'

      get '/user_profile', to: 'users#user_profile'

      match "/users" => 'users#update', via: [:put, :patch]
      
      delete '/users', to: 'users#destroy'

      get '/users', to: 'users#show'

      get '/password_reset', to: 'users#send_password_reset'

      post '/password_reset', to: 'users#reset_password'

       
      match "/recipe_items" => "recipe_items#update", via: [:put, :patch]

      delete '/recipe_items', to: 'recipe_items#destroy'
      
      get '/recipe_items', to: 'recipe_items#show'

      get '/steps', to: 'steps#show'

      delete '/steps', to: 'steps#destroy'

      match "/steps" => "steps#update", via: [:put, :patch]

      resources :recipe_items
        
      resources :steps
     
      resources :cards
       
      resources :workflows

      resources :ingredients

    end
  
  end

end

app/models/step.rb
class Step
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  # fields
  field :comment, type: String
  field :s_order, type: String

  # relations
  embedded_in :recipe_item
  embeds_many :cards
  accepts_nested_attributes_for :cards

end

app/controllers/api/v1/steps_controller.rb
class Api::V1::StepsController < Api::V1::BaseController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_recipe
  before_action :set_step, only: [:show, :edit, :update, :destroy]


  # GET /steps.json
  def index
    @steps = @recipe_item.steps.all
  rescue => e
    render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # GET /steps/1.json
  def show
    render json: @step
  rescue => e
    render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # POST /steps.json
  def create
    @step = @recipe_item.steps.new(step_params)
    if @step.save
      render json: @step
    else
      render json: @step.errors
    end
  rescue => e
    render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # PATCH/PUT /steps/1.json
  def update
    if @step.update(step_params)
      render json: @step
    else
      render json: @step.errors
    end
  rescue => e
    render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # DELETE /steps/1.json
  def destroy
    @step.destroy
    render json: { head: :no_content }
  rescue => e
    render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = @recipe_item.steps.find(params[:id])
    end

    def set_recipe
      @recipe_item = RecipeItem.find(params[:recipe_item_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:recipe_item_id, :comment, cards: [:c_type, :c_id, :c_varient]
)
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :update, :destroy]
  
  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    def set_recipe
      @recipe_item = RecipeItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:recipe_item_id, :comment)
    end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_item_id %><br>
    <%= f.number_field :recipe_item_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>Recipe item</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.recipe_item_id %></td>
        <td><%= step.comment %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe item:</strong>
  <%= @step.recipe_item_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @step.comment %>
</p>

<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>