config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  namespace :api do
    
    namespace :v1, defaults:{format: 'json'} do
      
      get '/ingredients_search', to: 'ingredients#ingredients_search'

      get '/workflows_search', to: 'workflows#workflows_search'
      

      post '/create_user', to: 'authentications#create_user'

      get '/user_profile', to: 'users#user_profile'

      match "/users" => 'users#update', via: [:put, :patch]
      
      delete '/users', to: 'users#destroy'

      get '/users', to: 'users#show'

      get '/password_reset', to: 'users#send_password_reset'

      post '/password_reset', to: 'users#reset_password'

       
      match "/recipe_items" => "recipe_items#update", via: [:put, :patch]

      delete '/recipe_items', to: 'recipe_items#destroy'
      
      get '/recipe_items', to: 'recipe_items#show'

      get '/steps', to: 'steps#show'

      delete '/steps', to: 'steps#destroy'

      match "/steps" => "steps#update", via: [:put, :patch]

      resources :recipe_items
        
      resources :steps
     
      resources :cards
       
      resources :workflows

      resources :ingredients

    end
  
  end

end

app/models/card.rb
class Card
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  # fields
  field :c_id, type: Integer
  field :c_type, type: String
  field :c_order, type: Integer
   
  # relations
  embedded_in :step


end

app/controllers/api/v1/cards_controller.rb
class Api::V1::CardsController <  Api::V1::BaseController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /cards.json
  def index
    @cards = Card.all
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # GET /cards/1.json
  def show
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # POST /cards.json
  def create
    @card = Card.new(card_params)
    if @card.save
      render json: @card
    else
      render json: @card.errors
    end
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # PATCH/PUT /cards/1.json
  def update
    if @card.update(card_params)
      render json: @card
    else
      render json: @card.errors
    end
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  # DELETE /cards/1.json
  def destroy
    @card.destroy
    json: { head :no_content }
  rescue => e
     render json: {error_code: Code[:error_rescue], error_message: e.message}, status: Code[:status_error]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:step_id, :c_id, :c_type, :c_order)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:step_id, :c_id, :c_type, :c_order)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :step_id %><br>
    <%= f.number_field :step_id %>
  </div>
  <div class="field">
    <%= f.label :c_id %><br>
    <%= f.number_field :c_id %>
  </div>
  <div class="field">
    <%= f.label :c_type %><br>
    <%= f.text_field :c_type %>
  </div>
  <div class="field">
    <%= f.label :c_order %><br>
    <%= f.number_field :c_order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th>Step</th>
      <th>C</th>
      <th>C type</th>
      <th>C order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.step_id %></td>
        <td><%= card.c_id %></td>
        <td><%= card.c_type %></td>
        <td><%= card.c_order %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Step:</strong>
  <%= @card.step_id %>
</p>

<p>
  <strong>C:</strong>
  <%= @card.c_id %>
</p>

<p>
  <strong>C type:</strong>
  <%= @card.c_type %>
</p>

<p>
  <strong>C order:</strong>
  <%= @card.c_order %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>